defensive_stats = {
    "Ohio State": {
        "games_played": 14,
        "points_allowed": 130,
        "points_allowed_per_game": 9.3,
        "rushing_yards_allowed": 1251,
        "rushing_yards_allowed_per_game": 89.4,
        "passing_yards_allowed": 1587,
        "passing_yards_allowed_per_game": 113.4,
        "total_yards_allowed": 2838,
        "total_yards_allowed_per_game": 202.7,
        "takeaways": 15,
    },
    "Indiana": {
        "games_played": 16,
        "points_allowed": 187,
        "points_allowed_per_game": 11.7,
        "rushing_yards_allowed": 1235,
        "rushing_yards_allowed_per_game": 77.2,
        "passing_yards_allowed": 2731,
        "passing_yards_allowed_per_game": 170.7,
        "total_yards_allowed": 3966,
        "total_yards_allowed_per_game": 247.9,
        "takeaways": 30,
    },
    "Oregon": {
        "games_played": 15,
        "points_allowed": 268,
        "points_allowed_per_game": 17.9,
        "rushing_yards_allowed": 1736,
        "rushing_yards_allowed_per_game": 115.7,
        "passing_yards_allowed": 2168,
        "passing_yards_allowed_per_game": 144.5,
        "total_yards_allowed": 3904,
        "total_yards_allowed_per_game": 260.3,
        "takeaways": 21,
    },
    "Iowa": {
        "games_played": 13,
        "points_allowed": 209,
        "points_allowed_per_game": 16.1,
        "rushing_yards_allowed": 1400,
        "rushing_yards_allowed_per_game": 107.7,
        "passing_yards_allowed": 2065,
        "passing_yards_allowed_per_game": 158.8,
        "total_yards_allowed": 3465,
        "total_yards_allowed_per_game": 266.5,
        "takeaways": 14,
    },
    "Washington": {
        "games_played": 13,
        "points_allowed": 243,
        "points_allowed_per_game": 18.7,
        "rushing_yards_allowed": 1302,
        "rushing_yards_allowed_per_game": 100.2,
        "passing_yards_allowed": 2591,
        "passing_yards_allowed_per_game": 199.3,
        "total_yards_allowed": 3893,
        "total_yards_allowed_per_game": 299.5,
        "takeaways": 19,
    },
    "Wisconsin": {
        "games_played": 12,
        "points_allowed": 259,
        "points_allowed_per_game": 21.6,
        "rushing_yards_allowed": 1264,
        "rushing_yards_allowed_per_game": 105.3,
        "passing_yards_allowed": 2408,
        "passing_yards_allowed_per_game": 200.7,
        "total_yards_allowed": 3672,
        "total_yards_allowed_per_game": 306.0,
        "takeaways": 6,
    },
    "Michigan": {
        "games_played": 13,
        "points_allowed": 265,
        "points_allowed_per_game": 20.4,
        "rushing_yards_allowed": 1455,
        "rushing_yards_allowed_per_game": 111.9,
        "passing_yards_allowed": 2526,
        "passing_yards_allowed_per_game": 194.3,
        "total_yards_allowed": 3981,
        "total_yards_allowed_per_game": 306.2,
        "takeaways": 19,
    },
    "Minnesota": {
        "games_played": 13,
        "points_allowed": 298,
        "points_allowed_per_game": 22.9,
        "rushing_yards_allowed": 1574,
        "rushing_yards_allowed_per_game": 121.1,
        "passing_yards_allowed": 2461,
        "passing_yards_allowed_per_game": 189.3,
        "total_yards_allowed": 4035,
        "total_yards_allowed_per_game": 310.4,
        "takeaways": 16,
    },
    "Penn State": {
        "games_played": 13,
        "points_allowed": 267,
        "points_allowed_per_game": 20.5,
        "rushing_yards_allowed": 1853,
        "rushing_yards_allowed_per_game": 142.5,
        "passing_yards_allowed": 2186,
        "passing_yards_allowed_per_game": 168.2,
        "total_yards_allowed": 4039,
        "total_yards_allowed_per_game": 310.7,
        "takeaways": 13,
    },
    "Nebraska": {
        "games_played": 13,
        "points_allowed": 320,
        "points_allowed_per_game": 24.6,
        "rushing_yards_allowed": 2294,
        "rushing_yards_allowed_per_game": 176.5,
        "passing_yards_allowed": 1842,
        "passing_yards_allowed_per_game": 141.7,
        "total_yards_allowed": 4136,
        "total_yards_allowed_per_game": 318.2,
        "takeaways": 13,
    },
    "Illinois": {
        "games_played": 13,
        "points_allowed": 307,
        "points_allowed_per_game": 23.6,
        "rushing_yards_allowed": 1647,
        "rushing_yards_allowed_per_game": 126.7,
        "passing_yards_allowed": 2700,
        "passing_yards_allowed_per_game": 207.7,
        "total_yards_allowed": 4347,
        "total_yards_allowed_per_game": 334.4,
        "takeaways": 16,
    },
    "USC": {
        "games_played": 13,
        "points_allowed": 299,
        "points_allowed_per_game": 23.0,
        "rushing_yards_allowed": 1862,
        "rushing_yards_allowed_per_game": 143.2,
        "passing_yards_allowed": 2494,
        "passing_yards_allowed_per_game": 191.8,
        "total_yards_allowed": 4356,
        "total_yards_allowed_per_game": 335.1,
        "takeaways": 18,
    },
    "Northwestern": {
        "games_played": 12,
        "points_allowed": 251,
        "points_allowed_per_game": 20.9,
        "rushing_yards_allowed": 1772,
        "rushing_yards_allowed_per_game": 147.7,
        "passing_yards_allowed": 2367,
        "passing_yards_allowed_per_game": 197.2,
        "total_yards_allowed": 4139,
        "total_yards_allowed_per_game": 344.9,
        "takeaways": 20,
    },
    "Michigan State": {
        "games_played": 12,
        "points_allowed": 359,
        "points_allowed_per_game": 29.9,
        "rushing_yards_allowed": 1768,
        "rushing_yards_allowed_per_game": 147.3,
        "passing_yards_allowed": 2668,
        "passing_yards_allowed_per_game": 222.3,
        "total_yards_allowed": 4436,
        "total_yards_allowed_per_game": 369.7,
        "takeaways": 9,
    },
    "UCLA": {
        "games_played": 12,
        "points_allowed": 401,
        "points_allowed_per_game": 33.4,
        "rushing_yards_allowed": 2285,
        "rushing_yards_allowed_per_game": 190.4,
        "passing_yards_allowed": 2284,
        "passing_yards_allowed_per_game": 190.3,
        "total_yards_allowed": 4569,
        "total_yards_allowed_per_game": 380.8,
        "takeaways": 10,
    },
    "Purdue": {
        "games_played": 12,
        "points_allowed": 382,
        "points_allowed_per_game": 31.8,
        "rushing_yards_allowed": 2182,
        "rushing_yards_allowed_per_game": 181.8,
        "passing_yards_allowed": 2758,
        "passing_yards_allowed_per_game": 229.8,
        "total_yards_allowed": 4940,
        "total_yards_allowed_per_game": 411.7,
        "takeaways": 9,
    },
    "Maryland": {
        "games_played": 12,
        "points_allowed": 309,
        "points_allowed_per_game": 28.1,
        "rushing_yards_allowed": 2107,
        "rushing_yards_allowed_per_game": 191.5,
        "passing_yards_allowed": 2534,
        "passing_yards_allowed_per_game": 230.4,
        "total_yards_allowed": 4641,
        "total_yards_allowed_per_game": 421.9,
        "takeaways": 21,
    },
    "Rutgers": {
        "games_played": 12,
        "points_allowed": 382,
        "points_allowed_per_game": 31.8,
        "rushing_yards_allowed": 2519,
        "rushing_yards_allowed_per_game": 209.9,
        "passing_yards_allowed": 2609,
        "passing_yards_allowed_per_game": 217.4,
        "total_yards_allowed": 5128,
        "total_yards_allowed_per_game": 427.3,
        "takeaways": 11,
    },
    "Miami": {
       "games_played": 16,
       "points_allowed": 237,
       "points_allowed_per_game": 14.8,
       "rushing_yards_allowed": 1428,
       "rushing_yards_allowed_per_game": 89.2,
       "passing_yards_allowed": 2944,
       "passing_yards_allowed_per_game": 184.0,
       "total_yards_allowed": 4372,
       "total_yards_allowed_per_game": 273.2,
       "takeaways": 25,
   },
   "Louisville": {
       "games_played": 13,
       "points_allowed": 275,
       "points_allowed_per_game": 21.2,
       "rushing_yards_allowed": 1486,
       "rushing_yards_allowed_per_game": 114.3,
       "passing_yards_allowed": 2252,
       "passing_yards_allowed_per_game": 173.2,
       "total_yards_allowed": 3738,
       "total_yards_allowed_per_game": 287.5,
       "takeaways": 20,
   },
   "Virginia": {
       "games_played": 14,
       "points_allowed": 274,
       "points_allowed_per_game": 19.6,
       "rushing_yards_allowed": 1603,
       "rushing_yards_allowed_per_game": 114.5,
       "passing_yards_allowed": 2538,
       "passing_yards_allowed_per_game": 181.3,
       "total_yards_allowed": 4141,
       "total_yards_allowed_per_game": 295.8,
       "takeaways": 21,
   },
   "Pittsburgh": {
       "games_played": 13,
       "points_allowed": 322,
       "points_allowed_per_game": 24.8,
       "rushing_yards_allowed": 1236,
       "rushing_yards_allowed_per_game": 95.1,
       "passing_yards_allowed": 2794,
       "passing_yards_allowed_per_game": 214.9,
       "total_yards_allowed": 4030,
       "total_yards_allowed_per_game": 310.0,
       "takeaways": 21,
   },
   "Florida State": {
       "games_played": 12,
       "points_allowed": 264,
       "points_allowed_per_game": 22.0,
       "rushing_yards_allowed": 1657,
       "rushing_yards_allowed_per_game": 138.1,
       "passing_yards_allowed": 2082,
       "passing_yards_allowed_per_game": 173.5,
       "total_yards_allowed": 3739,
       "total_yards_allowed_per_game": 311.6,
       "takeaways": 14,
   },
   "Wake Forest": {
       "games_played": 13,
       "points_allowed": 287,
       "points_allowed_per_game": 22.1,
       "rushing_yards_allowed": 1581,
       "rushing_yards_allowed_per_game": 121.6,
       "passing_yards_allowed": 2504,
       "passing_yards_allowed_per_game": 192.6,
       "total_yards_allowed": 4085,
       "total_yards_allowed_per_game": 314.2,
       "takeaways": 15,
   },
   "North Carolina": {
       "games_played": 12,
       "points_allowed": 294,
       "points_allowed_per_game": 24.5,
       "rushing_yards_allowed": 1503,
       "rushing_yards_allowed_per_game": 125.2,
       "passing_yards_allowed": 2301,
       "passing_yards_allowed_per_game": 191.8,
       "total_yards_allowed": 3804,
       "total_yards_allowed_per_game": 317.0,
       "takeaways": 12,
   },
   "Clemson": {
       "games_played": 13,
       "points_allowed": 267,
       "points_allowed_per_game": 20.5,
       "rushing_yards_allowed": 1369,
       "rushing_yards_allowed_per_game": 105.3,
       "passing_yards_allowed": 3074,
       "passing_yards_allowed_per_game": 236.5,
       "total_yards_allowed": 4443,
       "total_yards_allowed_per_game": 341.8,
       "takeaways": 17,
   },
   "California": {
       "games_played": 13,
       "points_allowed": 353,
       "points_allowed_per_game": 27.2,
       "rushing_yards_allowed": 2033,
       "rushing_yards_allowed_per_game": 156.4,
       "passing_yards_allowed": 2532,
       "passing_yards_allowed_per_game": 194.8,
       "total_yards_allowed": 4565,
       "total_yards_allowed_per_game": 351.2,
       "takeaways": 13,
   },
   "Virginia Tech": {
       "games_played": 12,
       "points_allowed": 362,
       "points_allowed_per_game": 30.2,
       "rushing_yards_allowed": 1839,
       "rushing_yards_allowed_per_game": 153.2,
       "passing_yards_allowed": 2548,
       "passing_yards_allowed_per_game": 212.3,
       "total_yards_allowed": 4387,
       "total_yards_allowed_per_game": 365.6,
       "takeaways": 6,
   },
   "SMU": {
       "games_played": 13,
       "points_allowed": 267,
       "points_allowed_per_game": 20.5,
       "rushing_yards_allowed": 1455,
       "rushing_yards_allowed_per_game": 111.9,
       "passing_yards_allowed": 3446,
       "passing_yards_allowed_per_game": 265.1,
       "total_yards_allowed": 4901,
       "total_yards_allowed_per_game": 377.0,
       "takeaways": 28,
   },
   "Georgia Tech": {
       "games_played": 13,
       "points_allowed": 325,
       "points_allowed_per_game": 25.0,
       "rushing_yards_allowed": 2136,
       "rushing_yards_allowed_per_game": 164.3,
       "passing_yards_allowed": 2876,
       "passing_yards_allowed_per_game": 221.2,
       "total_yards_allowed": 5012,
       "total_yards_allowed_per_game": 385.5,
       "takeaways": 9,
   },
   "Stanford": {
       "games_played": 12,
       "points_allowed": 350,
       "points_allowed_per_game": 29.2,
       "rushing_yards_allowed": 1431,
       "rushing_yards_allowed_per_game": 119.2,
       "passing_yards_allowed": 3297,
       "passing_yards_allowed_per_game": 274.8,
       "total_yards_allowed": 4728,
       "total_yards_allowed_per_game": 394.0,
       "takeaways": 13,
   },
   "NC State": {
       "games_played": 13,
       "points_allowed": 353,
       "points_allowed_per_game": 27.2,
       "rushing_yards_allowed": 1804,
       "rushing_yards_allowed_per_game": 138.8,
       "passing_yards_allowed": 3425,
       "passing_yards_allowed_per_game": 263.5,
       "total_yards_allowed": 5229,
       "total_yards_allowed_per_game": 402.2,
       "takeaways": 16,
   },
   "Duke": {
       "games_played": 14,
       "points_allowed": 412,
       "points_allowed_per_game": 29.4,
       "rushing_yards_allowed": 2064,
       "rushing_yards_allowed_per_game": 147.4,
       "passing_yards_allowed": 3715,
       "passing_yards_allowed_per_game": 265.4,
       "total_yards_allowed": 5779,
       "total_yards_allowed_per_game": 412.8,
       "takeaways": 24,
   },
   "Syracuse": {
       "games_played": 12,
       "points_allowed": 419,
       "points_allowed_per_game": 34.9,
       "rushing_yards_allowed": 2101,
       "rushing_yards_allowed_per_game": 175.1,
       "passing_yards_allowed": 2903,
       "passing_yards_allowed_per_game": 241.9,
       "total_yards_allowed": 5004,
       "total_yards_allowed_per_game": 417.0,
       "takeaways": 10,
   },
   "Boston College": {
       "games_played": 12,
       "points_allowed": 393,
       "points_allowed_per_game": 32.8,
       "rushing_yards_allowed": 2131,
       "rushing_yards_allowed_per_game": 177.6,
       "passing_yards_allowed": 2962,
       "passing_yards_allowed_per_game": 246.8,
       "total_yards_allowed": 5093,
       "total_yards_allowed_per_game": 424.4,
       "takeaways": 12,
   },
   "Texas Tech": {
        "games_played": 14,
        "points_allowed": 165,
        "points_allowed_per_game": 11.8,
        "rushing_yards_allowed": 982,
        "rushing_yards_allowed_per_game": 70.1,
        "passing_yards_allowed": 2346,
        "passing_yards_allowed_per_game": 167.6,
        "total_yards_allowed": 3328,
        "total_yards_allowed_per_game": 237.7,
        "takeaways": 32,
    },
    "Arizona": {
        "games_played": 13,
        "points_allowed": 251,
        "points_allowed_per_game": 19.3,
        "rushing_yards_allowed": 1862,
        "rushing_yards_allowed_per_game": 143.2,
        "passing_yards_allowed": 2019,
        "passing_yards_allowed_per_game": 155.3,
        "total_yards_allowed": 3881,
        "total_yards_allowed_per_game": 298.5,
        "takeaways": 31,
    },
    "BYU": {
        "games_played": 14,
        "points_allowed": 268,
        "points_allowed_per_game": 19.1,
        "rushing_yards_allowed": 1718,
        "rushing_yards_allowed_per_game": 122.7,
        "passing_yards_allowed": 2740,
        "passing_yards_allowed_per_game": 195.7,
        "total_yards_allowed": 4458,
        "total_yards_allowed_per_game": 318.4,
        "takeaways": 24,
    },
    "UCF": {
        "games_played": 12,
        "points_allowed": 283,
        "points_allowed_per_game": 23.6,
        "rushing_yards_allowed": 1808,
        "rushing_yards_allowed_per_game": 150.7,
        "passing_yards_allowed": 2064,
        "passing_yards_allowed_per_game": 172.0,
        "total_yards_allowed": 3872,
        "total_yards_allowed_per_game": 322.7,
        "takeaways": 14,
    },
    "Houston": {
        "games_played": 13,
        "points_allowed": 297,
        "points_allowed_per_game": 22.8,
        "rushing_yards_allowed": 1677,
        "rushing_yards_allowed_per_game": 129.0,
        "passing_yards_allowed": 2664,
        "passing_yards_allowed_per_game": 204.9,
        "total_yards_allowed": 4341,
        "total_yards_allowed_per_game": 333.9,
        "takeaways": 18,
    },
    "Arizona State": {
        "games_played": 13,
        "points_allowed": 318,
        "points_allowed_per_game": 24.5,
        "rushing_yards_allowed": 1612,
        "rushing_yards_allowed_per_game": 124.0,
        "passing_yards_allowed": 2798,
        "passing_yards_allowed_per_game": 215.2,
        "total_yards_allowed": 4410,
        "total_yards_allowed_per_game": 339.2,
        "takeaways": 15,
    },
    "Utah": {
        "games_played": 13,
        "points_allowed": 246,
        "points_allowed_per_game": 18.9,
        "rushing_yards_allowed": 2341,
        "rushing_yards_allowed_per_game": 180.1,
        "passing_yards_allowed": 2085,
        "passing_yards_allowed_per_game": 160.4,
        "total_yards_allowed": 4426,
        "total_yards_allowed_per_game": 340.5,
        "takeaways": 18,
    },
    "Iowa State": {
        "games_played": 12,
        "points_allowed": 242,
        "points_allowed_per_game": 20.2,
        "rushing_yards_allowed": 1656,
        "rushing_yards_allowed_per_game": 138.0,
        "passing_yards_allowed": 2549,
        "passing_yards_allowed_per_game": 212.4,
        "total_yards_allowed": 4205,
        "total_yards_allowed_per_game": 350.4,
        "takeaways": 18,
    },
    "TCU": {
        "games_played": 13,
        "points_allowed": 329,
        "points_allowed_per_game": 25.3,
        "rushing_yards_allowed": 1730,
        "rushing_yards_allowed_per_game": 133.1,
        "passing_yards_allowed": 3059,
        "passing_yards_allowed_per_game": 235.3,
        "total_yards_allowed": 4789,
        "total_yards_allowed_per_game": 368.4,
        "takeaways": 21,
    },
    "Kansas State": {
        "games_played": 12,
        "points_allowed": 320,
        "points_allowed_per_game": 26.7,
        "rushing_yards_allowed": 1965,
        "rushing_yards_allowed_per_game": 163.8,
        "passing_yards_allowed": 2456,
        "passing_yards_allowed_per_game": 204.7,
        "total_yards_allowed": 4421,
        "total_yards_allowed_per_game": 368.4,
        "takeaways": 26,
    },
    "Kansas": {
        "games_played": 12,
        "points_allowed": 321,
        "points_allowed_per_game": 26.8,
        "rushing_yards_allowed": 2078,
        "rushing_yards_allowed_per_game": 173.2,
        "passing_yards_allowed": 2430,
        "passing_yards_allowed_per_game": 202.5,
        "total_yards_allowed": 4508,
        "total_yards_allowed_per_game": 375.7,
        "takeaways": 10,
    },
    "Baylor": {
        "games_played": 12,
        "points_allowed": 391,
        "points_allowed_per_game": 32.6,
        "rushing_yards_allowed": 2366,
        "rushing_yards_allowed_per_game": 197.2,
        "passing_yards_allowed": 2272,
        "passing_yards_allowed_per_game": 189.3,
        "total_yards_allowed": 4638,
        "total_yards_allowed_per_game": 386.5,
        "takeaways": 11,
    },
    "Cincinnati": {
        "games_played": 13,
        "points_allowed": 333,
        "points_allowed_per_game": 25.6,
        "rushing_yards_allowed": 2320,
        "rushing_yards_allowed_per_game": 178.5,
        "passing_yards_allowed": 2751,
        "passing_yards_allowed_per_game": 211.6,
        "total_yards_allowed": 5071,
        "total_yards_allowed_per_game": 390.1,
        "takeaways": 10,
    },
    "West Virginia": {
        "games_played": 12,
        "points_allowed": 370,
        "points_allowed_per_game": 30.8,
        "rushing_yards_allowed": 1725,
        "rushing_yards_allowed_per_game": 143.8,
        "passing_yards_allowed": 3015,
        "passing_yards_allowed_per_game": 251.2,
        "total_yards_allowed": 4740,
        "total_yards_allowed_per_game": 395.0,
        "takeaways": 20,
    },
    "Oklahoma State": {
        "games_played": 12,
        "points_allowed": 400,
        "points_allowed_per_game": 33.3,
        "rushing_yards_allowed": 2003,
        "rushing_yards_allowed_per_game": 166.9,
        "passing_yards_allowed": 2897,
        "passing_yards_allowed_per_game": 241.4,
        "total_yards_allowed": 4900,
        "total_yards_allowed_per_game": 408.3,
        "takeaways": 12,
    },
    "Colorado": {
        "games_played": 12,
        "points_allowed": 366,
        "points_allowed_per_game": 30.5,
        "rushing_yards_allowed": 2670,
        "rushing_yards_allowed_per_game": 222.5,
        "passing_yards_allowed": 2361,
        "passing_yards_allowed_per_game": 196.8,
        "total_yards_allowed": 5031,
        "total_yards_allowed_per_game": 419.2,
        "takeaways": 15,
    },
    "Oklahoma": {
        "games_played": 13,
        "points_allowed": 201,
        "points_allowed_per_game": 15.5,
        "rushing_yards_allowed": 1005,
        "rushing_yards_allowed_per_game": 77.3,
        "passing_yards_allowed": 2244,
        "passing_yards_allowed_per_game": 172.6,
        "total_yards_allowed": 3249,
        "total_yards_allowed_per_game": 249.9,
        "takeaways": 13,
    },
    "Missouri": {
        "games_played": 13,
        "points_allowed": 246,
        "points_allowed_per_game": 18.9,
        "rushing_yards_allowed": 1350,
        "rushing_yards_allowed_per_game": 103.8,
        "passing_yards_allowed": 1998,
        "passing_yards_allowed_per_game": 153.7,
        "total_yards_allowed": 3348,
        "total_yards_allowed_per_game": 257.5,
        "takeaways": 12,
    },
    "Alabama": {
        "games_played": 15,
        "points_allowed": 288,
        "points_allowed_per_game": 19.2,
        "rushing_yards_allowed": 1903,
        "rushing_yards_allowed_per_game": 126.9,
        "passing_yards_allowed": 2322,
        "passing_yards_allowed_per_game": 154.8,
        "total_yards_allowed": 4225,
        "total_yards_allowed_per_game": 281.7,
        "takeaways": 20,
    },
    "Texas A&M": {
        "games_played": 13,
        "points_allowed": 273,
        "points_allowed_per_game": 21.0,
        "rushing_yards_allowed": 1700,
        "rushing_yards_allowed_per_game": 130.8,
        "passing_yards_allowed": 1978,
        "passing_yards_allowed_per_game": 152.2,
        "total_yards_allowed": 3678,
        "total_yards_allowed_per_game": 282.9,
        "takeaways": 10,
    },
    "Georgia": {
        "games_played": 14,
        "points_allowed": 246,
        "points_allowed_per_game": 17.6,
        "rushing_yards_allowed": 1141,
        "rushing_yards_allowed_per_game": 81.5,
        "passing_yards_allowed": 2911,
        "passing_yards_allowed_per_game": 207.9,
        "total_yards_allowed": 4052,
        "total_yards_allowed_per_game": 289.4,
        "takeaways": 13,
    },
    "LSU": {
        "games_played": 13,
        "points_allowed": 258,
        "points_allowed_per_game": 19.8,
        "rushing_yards_allowed": 1607,
        "rushing_yards_allowed_per_game": 123.6,
        "passing_yards_allowed": 2457,
        "passing_yards_allowed_per_game": 189.0,
        "total_yards_allowed": 4064,
        "total_yards_allowed_per_game": 312.6,
        "takeaways": 21,
    },
    "Auburn": {
        "games_played": 12,
        "points_allowed": 248,
        "points_allowed_per_game": 20.7,
        "rushing_yards_allowed": 1192,
        "rushing_yards_allowed_per_game": 99.3,
        "passing_yards_allowed": 2584,
        "passing_yards_allowed_per_game": 215.3,
        "total_yards_allowed": 3776,
        "total_yards_allowed_per_game": 314.7,
        "takeaways": 17,
    },
    "Texas": {
        "games_played": 13,
        "points_allowed": 264,
        "points_allowed_per_game": 20.3,
        "rushing_yards_allowed": 1355,
        "rushing_yards_allowed_per_game": 104.2,
        "passing_yards_allowed": 2804,
        "passing_yards_allowed_per_game": 215.7,
        "total_yards_allowed": 4159,
        "total_yards_allowed_per_game": 319.9,
        "takeaways": 23,
    },
    "Mississippi": {
        "games_played": 15,
        "points_allowed": 316,
        "points_allowed_per_game": 21.1,
        "rushing_yards_allowed": 2236,
        "rushing_yards_allowed_per_game": 149.1,
        "passing_yards_allowed": 2793,
        "passing_yards_allowed_per_game": 186.2,
        "total_yards_allowed": 5029,
        "total_yards_allowed_per_game": 335.3,
        "takeaways": 15,
    },
    "Vanderbilt": {
        "games_played": 13,
        "points_allowed": 297,
        "points_allowed_per_game": 22.8,
        "rushing_yards_allowed": 1406,
        "rushing_yards_allowed_per_game": 108.2,
        "passing_yards_allowed": 3019,
        "passing_yards_allowed_per_game": 232.2,
        "total_yards_allowed": 4425,
        "total_yards_allowed_per_game": 340.4,
        "takeaways": 15,
    },
    "South Carolina": {
        "games_played": 12,
        "points_allowed": 265,
        "points_allowed_per_game": 22.1,
        "rushing_yards_allowed": 1640,
        "rushing_yards_allowed_per_game": 136.7,
        "passing_yards_allowed": 2467,
        "passing_yards_allowed_per_game": 205.6,
        "total_yards_allowed": 4107,
        "total_yards_allowed_per_game": 342.2,
        "takeaways": 22,
    },
    "Kentucky": {
        "games_played": 12,
        "points_allowed": 317,
        "points_allowed_per_game": 26.4,
        "rushing_yards_allowed": 1611,
        "rushing_yards_allowed_per_game": 134.2,
        "passing_yards_allowed": 2706,
        "passing_yards_allowed_per_game": 225.5,
        "total_yards_allowed": 4317,
        "total_yards_allowed_per_game": 359.8,
        "takeaways": 14,
    },
    "Florida": {
        "games_played": 12,
        "points_allowed": 288,
        "points_allowed_per_game": 24.0,
        "rushing_yards_allowed": 1847,
        "rushing_yards_allowed_per_game": 153.9,
        "passing_yards_allowed": 2537,
        "passing_yards_allowed_per_game": 211.4,
        "total_yards_allowed": 4384,
        "total_yards_allowed_per_game": 365.3,
        "takeaways": 17,
    },
    "Tennessee": {
        "games_played": 13,
        "points_allowed": 375,
        "points_allowed_per_game": 28.8,
        "rushing_yards_allowed": 1976,
        "rushing_yards_allowed_per_game": 152.0,
        "passing_yards_allowed": 2957,
        "passing_yards_allowed_per_game": 227.5,
        "total_yards_allowed": 4933,
        "total_yards_allowed_per_game": 379.5,
        "takeaways": 20,
    },
    "Mississippi State": {
        "games_played": 13,
        "points_allowed": 393,
        "points_allowed_per_game": 30.2,
        "rushing_yards_allowed": 2422,
        "rushing_yards_allowed_per_game": 186.3,
        "passing_yards_allowed": 2776,
        "passing_yards_allowed_per_game": 213.5,
        "total_yards_allowed": 5198,
        "total_yards_allowed_per_game": 399.8,
        "takeaways": 18,
    },
    "Arkansas": {
        "games_played": 12,
        "points_allowed": 406,
        "points_allowed_per_game": 33.8,
        "rushing_yards_allowed": 2231,
        "rushing_yards_allowed_per_game": 185.9,
        "passing_yards_allowed": 2730,
        "passing_yards_allowed_per_game": 227.5,
        "total_yards_allowed": 4961,
        "total_yards_allowed_per_game": 413.4,
        "takeaways": 9,
    },
    "Notre Dame": {
        "games_played": 12,
        "points_allowed": 211,
        "points_allowed_per_game": 17.6,
        "rushing_yards_allowed": 1186,
        "rushing_yards_allowed_per_game": 98.8,
        "passing_yards_allowed": 2329,
        "passing_yards_allowed_per_game": 194.1,
        "total_yards_allowed": 3515,
        "total_yards_allowed_per_game": 292.9,
        "takeaways": 23,
    },
}