offensive_stats = {
    "USC": {
        "games_played": 13,
        "points_scored": 465,
        "points_per_game": 35.8,
        "rushing_yards": 2203,
        "rushing_yards_per_game": 169.5,
        "passing_yards": 3757,
        "passing_yards_per_game": 289.0,
        "total_yards": 5960,
        "total_yards_per_game": 458.5,
        "turnovers": 16,
    },
    "Oregon": {
        "games_played": 15,
        "points_scored": 554,
        "points_per_game": 36.9,
        "rushing_yards": 2979,
        "rushing_yards_per_game": 198.6,
        "passing_yards": 3664,
        "passing_yards_per_game": 244.3,
        "total_yards": 6643,
        "total_yards_per_game": 442.9,
        "turnovers": 15,
    },
    "Indiana": {
        "games_played": 16,
        "points_scored": 666,
        "points_per_game": 41.6,
        "rushing_yards": 3406,
        "rushing_yards_per_game": 212.9,
        "passing_yards": 3671,
        "passing_yards_per_game": 229.4,
        "total_yards": 7077,
        "total_yards_per_game": 442.3,
        "turnovers": 8,
    },
    "Ohio State": {
        "games_played": 14,
        "points_scored": 468,
        "points_per_game": 33.4,
        "rushing_yards": 2161,
        "rushing_yards_per_game": 154.4,
        "passing_yards": 3645,
        "passing_yards_per_game": 260.4,
        "total_yards": 5806,
        "total_yards_per_game": 414.7,
        "turnovers": 11,
    },
    "Washington": {
        "games_played": 13,
        "points_scored": 443,
        "points_per_game": 34.1,
        "rushing_yards": 2152,
        "rushing_yards_per_game": 165.5,
        "passing_yards": 2966,
        "passing_yards_per_game": 228.2,
        "total_yards": 5118,
        "total_yards_per_game": 393.7,
        "turnovers": 14,
    },
    "Rutgers": {
        "games_played": 12,
        "points_scored": 344,
        "points_per_game": 28.7,
        "rushing_yards": 1692,
        "rushing_yards_per_game": 141.0,
        "passing_yards": 2979,
        "passing_yards_per_game": 248.2,
        "total_yards": 4671,
        "total_yards_per_game": 389.2,
        "turnovers": 11,
    },
    "Michigan": {
        "games_played": 13,
        "points_scored": 358,
        "points_per_game": 27.5,
        "rushing_yards": 2732,
        "rushing_yards_per_game": 210.2,
        "passing_yards": 2308,
        "passing_yards_per_game": 177.5,
        "total_yards": 5040,
        "total_yards_per_game": 387.7,
        "turnovers": 17,
    },
    "Maryland": {
        "games_played": 12,
        "points_scored": 262,
        "points_per_game": 23.8,
        "rushing_yards": 1266,
        "rushing_yards_per_game": 115.1,
        "passing_yards": 2997,
        "passing_yards_per_game": 272.5,
        "total_yards": 4263,
        "total_yards_per_game": 387.5,
        "turnovers": 14,
    },
    "Northwestern": {
        "games_played": 12,
        "points_scored": 262,
        "points_per_game": 21.8,
        "rushing_yards": 2082,
        "rushing_yards_per_game": 173.5,
        "passing_yards": 2286,
        "passing_yards_per_game": 190.5,
        "total_yards": 4368,
        "total_yards_per_game": 364.0,
        "turnovers": 21,
    },
    "Illinois": {
        "games_played": 13,
        "points_scored": 382,
        "points_per_game": 29.4,
        "rushing_yards": 1795,
        "rushing_yards_per_game": 138.1,
        "passing_yards": 2838,
        "passing_yards_per_game": 218.3,
        "total_yards": 4633,
        "total_yards_per_game": 356.4,
        "turnovers": 11,
    },
    "Nebraska": {
        "games_played": 13,
        "points_scored": 373,
        "points_per_game": 28.7,
        "rushing_yards": 1897,
        "rushing_yards_per_game": 145.9,
        "passing_yards": 2698,
        "passing_yards_per_game": 207.5,
        "total_yards": 4595,
        "total_yards_per_game": 353.5,
        "turnovers": 11,
    },
    "Penn State": {
        "games_played": 13,
        "points_scored": 403,
        "points_per_game": 31.0,
        "rushing_yards": 2265,
        "rushing_yards_per_game": 174.2,
        "passing_yards": 2311,
        "passing_yards_per_game": 177.8,
        "total_yards": 4576,
        "total_yards_per_game": 352.0,
        "turnovers": 10,
    },
    "Purdue": {
        "games_played": 12,
        "points_scored": 225,
        "points_per_game": 18.8,
        "rushing_yards": 1518,
        "rushing_yards_per_game": 126.5,
        "passing_yards": 2486,
        "passing_yards_per_game": 207.2,
        "total_yards": 4004,
        "total_yards_per_game": 333.7,
        "turnovers": 21,
    },
    "Michigan State": {
        "games_played": 12,
        "points_scored": 295,
        "points_per_game": 24.6,
        "rushing_yards": 1474,
        "rushing_yards_per_game": 122.8,
        "passing_yards": 2391,
        "passing_yards_per_game": 199.2,
        "total_yards": 3865,
        "total_yards_per_game": 322.1,
        "turnovers": 12,
    },
    "Iowa": {
        "games_played": 13,
        "points_scored": 381,
        "points_per_game": 29.3,
        "rushing_yards": 2300,
        "rushing_yards_per_game": 176.9,
        "passing_yards": 1765,
        "passing_yards_per_game": 135.8,
        "total_yards": 4065,
        "total_yards_per_game": 312.7,
        "turnovers": 13,
    },
    "UCLA": {
        "games_played": 12,
        "points_scored": 218,
        "points_per_game": 18.2,
        "rushing_yards": 1675,
        "rushing_yards_per_game": 139.6,
        "passing_yards": 2004,
        "passing_yards_per_game": 167.0,
        "total_yards": 3679,
        "total_yards_per_game": 306.6,
        "turnovers": 13,
    },
    "Minnesota": {
        "games_played": 13,
        "points_scored": 299,
        "points_per_game": 23.0,
        "rushing_yards": 1342,
        "rushing_yards_per_game": 103.2,
        "passing_yards": 2325,
        "passing_yards_per_game": 178.8,
        "total_yards": 3667,
        "total_yards_per_game": 282.1,
        "turnovers": 9,
    },
    "Wisconsin": {
        "games_played": 12,
        "points_scored": 154,
        "points_per_game": 12.8,
        "rushing_yards": 1400,
        "rushing_yards_per_game": 116.7,
        "passing_yards": 1416,
        "passing_yards_per_game": 118.0,
        "total_yards": 2816,
        "total_yards_per_game": 234.7,
        "turnovers": 17,
    },
    "Florida State": {
        "games_played": 12,
        "points_scored": 396,
        "points_per_game": 33.0,
        "rushing_yards": 2624,
        "rushing_yards_per_game": 218.7,
        "passing_yards": 2924,
        "passing_yards_per_game": 243.7,
        "total_yards": 5548,
        "total_yards_per_game": 462.3,
        "turnovers": 19,
    },
    "Georgia Tech": {
        "games_played": 13,
        "points_scored": 418,
        "points_per_game": 32.2,
        "rushing_yards": 2567,
        "rushing_yards_per_game": 197.5,
        "passing_yards": 3368,
        "passing_yards_per_game": 259.1,
        "total_yards": 5935,
        "total_yards_per_game": 456.5,
        "turnovers": 15,
    },
    "Duke": {
        "games_played": 14,
        "points_scored": 484,
        "points_per_game": 34.6,
        "rushing_yards": 1934,
        "rushing_yards_per_game": 138.1,
        "passing_yards": 3797,
        "passing_yards_per_game": 271.2,
        "total_yards": 5731,
        "total_yards_per_game": 409.4,
        "turnovers": 14,
    },
    "Virginia": {
        "games_played": 14,
        "points_scored": 431,
        "points_per_game": 30.8,
        "rushing_yards": 2502,
        "rushing_yards_per_game": 178.7,
        "passing_yards": 3222,
        "passing_yards_per_game": 230.1,
        "total_yards": 5724,
        "total_yards_per_game": 408.9,
        "turnovers": 14,
    },
    "SMU": {
        "games_played": 13,
        "points_scored": 419,
        "points_per_game": 32.2,
        "rushing_yards": 1740,
        "rushing_yards_per_game": 133.8,
        "passing_yards": 3488,
        "passing_yards_per_game": 268.3,
        "total_yards": 5228,
        "total_yards_per_game": 402.2,
        "turnovers": 19,
    },
    "Miami": {
        "games_played": 16,
        "points_scored": 495,
        "points_per_game": 30.9,
        "rushing_yards": 2415,
        "rushing_yards_per_game": 150.9,
        "passing_yards": 3930,
        "passing_yards_per_game": 245.6,
        "total_yards": 6345,
        "total_yards_per_game": 396.6,
        "turnovers": 15,
    },
    "Wake Forest": {
        "games_played": 13,
        "points_scored": 365,
        "points_per_game": 28.1,
        "rushing_yards": 2030,
        "rushing_yards_per_game": 156.2,
        "passing_yards": 2978,
        "passing_yards_per_game": 229.1,
        "total_yards": 5008,
        "total_yards_per_game": 385.2,
        "turnovers": 21,
    },
    "Clemson": {
        "games_played": 13,
        "points_scored": 354,
        "points_per_game": 27.2,
        "rushing_yards": 1618,
        "rushing_yards_per_game": 124.5,
        "passing_yards": 3327,
        "passing_yards_per_game": 255.9,
        "total_yards": 4945,
        "total_yards_per_game": 380.4,
        "turnovers": 15,
    },
    "NC State": {
        "games_played": 13,
        "points_scored": 393,
        "points_per_game": 30.2,
        "rushing_yards": 1905,
        "rushing_yards_per_game": 146.5,
        "passing_yards": 3028,
        "passing_yards_per_game": 232.9,
        "total_yards": 4933,
        "total_yards_per_game": 379.5,
        "turnovers": 13,
    },
    "Louisville": {
        "games_played": 13,
        "points_scored": 389,
        "points_per_game": 29.9,
        "rushing_yards": 2131,
        "rushing_yards_per_game": 163.9,
        "passing_yards": 2686,
        "passing_yards_per_game": 206.6,
        "total_yards": 4817,
        "total_yards_per_game": 370.5,
        "turnovers": 17,
    },
    "Pittsburgh": {
        "games_played": 13,
        "points_scored": 438,
        "points_per_game": 33.7,
        "rushing_yards": 1526,
        "rushing_yards_per_game": 117.4,
        "passing_yards": 3250,
        "passing_yards_per_game": 250.0,
        "total_yards": 4776,
        "total_yards_per_game": 367.4,
        "turnovers": 23,
    },
    "Boston College": {
        "games_played": 12,
        "points_scored": 305,
        "points_per_game": 25.4,
        "rushing_yards": 1247,
        "rushing_yards_per_game": 103.9,
        "passing_yards": 3147,
        "passing_yards_per_game": 262.2,
        "total_yards": 4394,
        "total_yards_per_game": 366.2,
        "turnovers": 21,
    },
    "California": {
        "games_played": 13,
        "points_scored": 329,
        "points_per_game": 25.3,
        "rushing_yards": 1063,
        "rushing_yards_per_game": 81.8,
        "passing_yards": 3346,
        "passing_yards_per_game": 257.4,
        "total_yards": 4409,
        "total_yards_per_game": 339.2,
        "turnovers": 16,
    },
    "Virginia Tech": {
        "games_played": 12,
        "points_scored": 257,
        "points_per_game": 21.4,
        "rushing_yards": 2189,
        "rushing_yards_per_game": 182.4,
        "passing_yards": 1791,
        "passing_yards_per_game": 149.2,
        "total_yards": 3980,
        "total_yards_per_game": 331.7,
        "turnovers": 14,
    },
    "Syracuse": {
        "games_played": 12,
        "points_scored": 242,
        "points_per_game": 20.2,
        "rushing_yards": 1473,
        "rushing_yards_per_game": 122.8,
        "passing_yards": 2375,
        "passing_yards_per_game": 197.9,
        "total_yards": 3848,
        "total_yards_per_game": 320.7,
        "turnovers": 23,
    },
    "Stanford": {
        "games_played": 12,
        "points_scored": 226,
        "points_per_game": 18.8,
        "rushing_yards": 1014,
        "rushing_yards_per_game": 84.5,
        "passing_yards": 2341,
        "passing_yards_per_game": 195.1,
        "total_yards": 3355,
        "total_yards_per_game": 279.6,
        "turnovers": 17,
    },
    "North Carolina": {
        "games_played": 12,
        "points_scored": 231,
        "points_per_game": 19.2,
        "rushing_yards": 1262,
        "rushing_yards_per_game": 105.2,
        "passing_yards": 2088,
        "passing_yards_per_game": 174.0,
        "total_yards": 3350,
        "total_yards_per_game": 279.2,
        "turnovers": 15,
    },
    "Utah": {
        "games_played": 13,
        "points_scored": 537,
        "points_per_game": 41.3,
        "rushing_yards": 3462,
        "rushing_yards_per_game": 266.3,
        "passing_yards": 2741,
        "passing_yards_per_game": 210.8,
        "total_yards": 6203,
        "total_yards_per_game": 477.2,
        "turnovers": 12,
    },
    "Texas Tech": {
        "games_played": 14,
        "points_scored": 552,
        "points_per_game": 39.4,
        "rushing_yards": 2560,
        "rushing_yards_per_game": 182.9,
        "passing_yards": 3691,
        "passing_yards_per_game": 263.6,
        "total_yards": 6251,
        "total_yards_per_game": 446.5,
        "turnovers": 18,
    },
    "Baylor": {
        "games_played": 12,
        "points_scored": 373,
        "points_per_game": 31.1,
        "rushing_yards": 1698,
        "rushing_yards_per_game": 141.5,
        "passing_yards": 3570,
        "passing_yards_per_game": 297.5,
        "total_yards": 5268,
        "total_yards_per_game": 439.0,
        "turnovers": 24,
    },
    "TCU": {
        "games_played": 13,
        "points_scored": 399,
        "points_per_game": 30.7,
        "rushing_yards": 1708,
        "rushing_yards_per_game": 131.4,
        "passing_yards": 3618,
        "passing_yards_per_game": 278.3,
        "total_yards": 5326,
        "total_yards_per_game": 409.7,
        "turnovers": 20,
    },
    "Cincinnati": {
        "games_played": 13,
        "points_scored": 394,
        "points_per_game": 30.3,
        "rushing_yards": 2303,
        "rushing_yards_per_game": 177.2,
        "passing_yards": 2952,
        "passing_yards_per_game": 227.1,
        "total_yards": 5255,
        "total_yards_per_game": 404.2,
        "turnovers": 14,
    },
    "Arizona State": {
        "games_played": 13,
        "points_scored": 335,
        "points_per_game": 25.8,
        "rushing_yards": 2503,
        "rushing_yards_per_game": 192.5,
        "passing_yards": 2748,
        "passing_yards_per_game": 211.4,
        "total_yards": 5251,
        "total_yards_per_game": 403.9,
        "turnovers": 21,
    },
    "BYU": {
        "games_played": 14,
        "points_scored": 440,
        "points_per_game": 31.4,
        "rushing_yards": 2497,
        "rushing_yards_per_game": 178.4,
        "passing_yards": 3010,
        "passing_yards_per_game": 215.0,
        "total_yards": 5507,
        "total_yards_per_game": 393.4,
        "turnovers": 15,
    },
    "Arizona": {
        "games_played": 13,
        "points_scored": 410,
        "points_per_game": 31.5,
        "rushing_yards": 1981,
        "rushing_yards_per_game": 152.4,
        "passing_yards": 3085,
        "passing_yards_per_game": 237.3,
        "total_yards": 5066,
        "total_yards_per_game": 389.7,
        "turnovers": 13,
    },
    "Houston": {
        "games_played": 13,
        "points_scored": 378,
        "points_per_game": 29.1,
        "rushing_yards": 2309,
        "rushing_yards_per_game": 177.6,
        "passing_yards": 2720,
        "passing_yards_per_game": 209.2,
        "total_yards": 5029,
        "total_yards_per_game": 386.8,
        "turnovers": 14,
    },
    "Iowa State": {
        "games_played": 12,
        "points_scored": 329,
        "points_per_game": 27.4,
        "rushing_yards": 2089,
        "rushing_yards_per_game": 174.1,
        "passing_yards": 2518,
        "passing_yards_per_game": 209.8,
        "total_yards": 4607,
        "total_yards_per_game": 383.9,
        "turnovers": 14,
    },
    "Kansas": {
        "games_played": 12,
        "points_scored": 337,
        "points_per_game": 28.1,
        "rushing_yards": 2046,
        "rushing_yards_per_game": 170.5,
        "passing_yards": 2477,
        "passing_yards_per_game": 206.4,
        "total_yards": 4523,
        "total_yards_per_game": 376.9,
        "turnovers": 13,
    },
    "UCF": {
        "games_played": 12,
        "points_scored": 292,
        "points_per_game": 24.3,
        "rushing_yards": 1896,
        "rushing_yards_per_game": 158.0,
        "passing_yards": 2547,
        "passing_yards_per_game": 212.2,
        "total_yards": 4443,
        "total_yards_per_game": 370.2,
        "turnovers": 18,
    },
    "Kansas State": {
        "games_played": 12,
        "points_scored": 353,
        "points_per_game": 29.4,
        "rushing_yards": 2056,
        "rushing_yards_per_game": 171.3,
        "passing_yards": 2321,
        "passing_yards_per_game": 193.4,
        "total_yards": 4377,
        "total_yards_per_game": 364.8,
        "turnovers": 15,
    },
    "West Virginia": {
        "games_played": 12,
        "points_scored": 261,
        "points_per_game": 21.8,
        "rushing_yards": 1928,
        "rushing_yards_per_game": 160.7,
        "passing_yards": 2091,
        "passing_yards_per_game": 174.2,
        "total_yards": 4019,
        "total_yards_per_game": 334.9,
        "turnovers": 18,
    },
    "Colorado": {
        "games_played": 12,
        "points_scored": 251,
        "points_per_game": 20.9,
        "rushing_yards": 1507,
        "rushing_yards_per_game": 125.6,
        "passing_yards": 2151,
        "passing_yards_per_game": 179.2,
        "total_yards": 3658,
        "total_yards_per_game": 304.8,
        "turnovers": 17,
    },
    "Oklahoma State": {
        "games_played": 12,
        "points_scored": 170,
        "points_per_game": 14.2,
        "rushing_yards": 1420,
        "rushing_yards_per_game": 118.3,
        "passing_yards": 1948,
        "passing_yards_per_game": 162.3,
        "total_yards": 3368,
        "total_yards_per_game": 280.7,
        "turnovers": 17,
    },
    "Mississippi": {
        "games_played": 15,
        "points_scored": 554,
        "points_per_game": 36.9,
        "rushing_yards": 2645,
        "rushing_yards_per_game": 176.3,
        "passing_yards": 4621,
        "passing_yards_per_game": 308.1,
        "total_yards": 7266,
        "total_yards_per_game": 484.4,
        "turnovers": 14,
    },
    "Tennessee": {
        "games_played": 13,
        "points_scored": 517,
        "points_per_game": 39.8,
        "rushing_yards": 2255,
        "rushing_yards_per_game": 173.5,
        "passing_yards": 3652,
        "passing_yards_per_game": 280.9,
        "total_yards": 5907,
        "total_yards_per_game": 454.4,
        "turnovers": 15,
    },
    "Vanderbilt": {
        "games_played": 13,
        "points_scored": 500,
        "points_per_game": 38.5,
        "rushing_yards": 2282,
        "rushing_yards_per_game": 175.5,
        "passing_yards": 3602,
        "passing_yards_per_game": 277.1,
        "total_yards": 5884,
        "total_yards_per_game": 452.6,
        "turnovers": 12,
    },
    "Texas A&M": {
        "games_played": 13,
        "points_scored": 439,
        "points_per_game": 33.8,
        "rushing_yards": 2401,
        "rushing_yards_per_game": 184.7,
        "passing_yards": 3296,
        "passing_yards_per_game": 253.5,
        "total_yards": 5697,
        "total_yards_per_game": 438.2,
        "turnovers": 19,
    },
    "Arkansas": {
        "games_played": 12,
        "points_scored": 395,
        "points_per_game": 32.9,
        "rushing_yards": 2303,
        "rushing_yards_per_game": 191.9,
        "passing_yards": 2919,
        "passing_yards_per_game": 243.2,
        "total_yards": 5222,
        "total_yards_per_game": 435.2,
        "turnovers": 20,
    },
    "Missouri": {
        "games_played": 13,
        "points_scored": 393,
        "points_per_game": 30.2,
        "rushing_yards": 2968,
        "rushing_yards_per_game": 228.3,
        "passing_yards": 2315,
        "passing_yards_per_game": 178.1,
        "total_yards": 5283,
        "total_yards_per_game": 406.4,
        "turnovers": 17,
    },
    "Georgia": {
        "games_played": 14,
        "points_scored": 449,
        "points_per_game": 32.1,
        "rushing_yards": 2550,
        "rushing_yards_per_game": 182.1,
        "passing_yards": 3010,
        "passing_yards_per_game": 215.0,
        "total_yards": 5560,
        "total_yards_per_game": 397.1,
        "turnovers": 13,
    },
    "Texas": {
        "games_played": 13,
        "points_scored": 396,
        "points_per_game": 30.5,
        "rushing_yards": 1791,
        "rushing_yards_per_game": 137.8,
        "passing_yards": 3121,
        "passing_yards_per_game": 240.1,
        "total_yards": 4912,
        "total_yards_per_game": 377.8,
        "turnovers": 9,
    },
    "Mississippi State": {
        "games_played": 13,
        "points_scored": 395,
        "points_per_game": 30.4,
        "rushing_yards": 2049,
        "rushing_yards_per_game": 157.6,
        "passing_yards": 2855,
        "passing_yards_per_game": 219.6,
        "total_yards": 4904,
        "total_yards_per_game": 377.2,
        "turnovers": 15,
    },
    "Auburn": {
        "games_played": 12,
        "points_scored": 321,
        "points_per_game": 26.8,
        "rushing_yards": 2122,
        "rushing_yards_per_game": 176.8,
        "passing_yards": 2115,
        "passing_yards_per_game": 176.2,
        "total_yards": 4237,
        "total_yards_per_game": 353.1,
        "turnovers": 8,
    },
    "Alabama": {
        "games_played": 15,
        "points_scored": 443,
        "points_per_game": 29.5,
        "rushing_yards": 1562,
        "rushing_yards_per_game": 104.1,
        "passing_yards": 3697,
        "passing_yards_per_game": 246.5,
        "total_yards": 5259,
        "total_yards_per_game": 350.6,
        "turnovers": 13,
    },
    "Oklahoma": {
        "games_played": 13,
        "points_scored": 341,
        "points_per_game": 26.2,
        "rushing_yards": 1540,
        "rushing_yards_per_game": 118.5,
        "passing_yards": 2886,
        "passing_yards_per_game": 222.0,
        "total_yards": 4426,
        "total_yards_per_game": 340.5,
        "turnovers": 16,
    },
    "Florida": {
        "games_played": 12,
        "points_scored": 259,
        "points_per_game": 21.6,
        "rushing_yards": 1641,
        "rushing_yards_per_game": 136.8,
        "passing_yards": 2347,
        "passing_yards_per_game": 195.6,
        "total_yards": 3988,
        "total_yards_per_game": 332.3,
        "turnovers": 18,
    },
    "Kentucky": {
        "games_played": 12,
        "points_scored": 276,
        "points_per_game": 23.0,
        "rushing_yards": 1670,
        "rushing_yards_per_game": 139.2,
        "passing_yards": 2234,
        "passing_yards_per_game": 186.2,
        "total_yards": 3904,
        "total_yards_per_game": 325.3,
        "turnovers": 22,
    },
    "LSU": {
        "games_played": 13,
        "points_scored": 297,
        "points_per_game": 22.8,
        "rushing_yards": 1352,
        "rushing_yards_per_game": 104.0,
        "passing_yards": 2763,
        "passing_yards_per_game": 212.5,
        "total_yards": 4115,
        "total_yards_per_game": 316.5,
        "turnovers": 14,
    },
    "South Carolina": {
        "games_played": 12,
        "points_scored": 272,
        "points_per_game": 22.7,
        "rushing_yards": 1346,
        "rushing_yards_per_game": 112.2,
        "passing_yards": 2344,
        "passing_yards_per_game": 195.3,
        "total_yards": 3690,
        "total_yards_per_game": 307.5,
        "turnovers": 18,
    },
    "Notre Dame": {
        "games_played": 12,
        "points_scored": 504,
        "points_per_game": 42.0,
        "rushing_yards": 2441,
        "rushing_yards_per_game": 203.4,
        "passing_yards": 2971,
        "passing_yards_per_game": 247.6,
        "total_yards": 5412,
        "total_yards_per_game": 451.0,
        "turnovers": 10,
    },
}