special_teams_stats = {
    "Miami": {
        "field_goals_attempted": 25,
        "field_goals_made": 18,
        "field_goal_percentage": 72.0,
        "extra_points_attempted": 61,
        "extra_points_made": 61,
        "extra_point_percentage": 100.0,
    },
    "Missouri": {
        "field_goals_attempted": 21,
        "field_goals_made": 15,
        "field_goal_percentage": 71.4,
        "extra_points_attempted": 44,
        "extra_points_made": 42,
        "extra_point_percentage": 95.5,
    },
    "TCU": {
        "field_goals_attempted": 15,
        "field_goals_made": 12,
        "field_goal_percentage": 80.0,
        "extra_points_attempted": 51,
        "extra_points_made": 51,
        "extra_point_percentage": 100.0,
    },
    "Northwestern": {
        "field_goals_attempted": 24,
        "field_goals_made": 22,
        "field_goal_percentage": 91.7,
        "extra_points_attempted": 27,
        "extra_points_made": 26,
        "extra_point_percentage": 96.3,
    },
    "Texas Tech": {
        "field_goals_attempted": 34,
        "field_goals_made": 28,
        "field_goal_percentage": 82.4,
        "extra_points_attempted": 61,
        "extra_points_made": 58,
        "extra_point_percentage": 95.1,
    },
    "Indiana": {
        "field_goals_attempted": 21,
        "field_goals_made": 19,
        "field_goal_percentage": 90.5,
        "extra_points_attempted": 87,
        "extra_points_made": 87,
        "extra_point_percentage": 100.0,
    },
    "Penn State": {
        "field_goals_attempted": 19,
        "field_goals_made": 18,
        "field_goal_percentage": 94.7,
        "extra_points_attempted": 46,
        "extra_points_made": 45,
        "extra_point_percentage": 97.8,
    },
    "Boston College": {
        "field_goals_attempted": 17,
        "field_goals_made": 16,
        "field_goal_percentage": 94.1,
        "extra_points_attempted": 35,
        "extra_points_made": 35,
        "extra_point_percentage": 100.0,
    },
    "Vanderbilt": {
        "field_goals_attempted": 14,
        "field_goals_made": 13,
        "field_goal_percentage": 92.9,
        "extra_points_attempted": 64,
        "extra_points_made": 63,
        "extra_point_percentage": 98.4,
    },
    "Georgia": {
        "field_goals_attempted": 19,
        "field_goals_made": 17,
        "field_goal_percentage": 89.5,
        "extra_points_attempted": 54,
        "extra_points_made": 54,
        "extra_point_percentage": 100.0,
    },
    "Oklahoma": {
        "field_goals_attempted": 28,
        "field_goals_made": 24,
        "field_goal_percentage": 85.7,
        "extra_points_attempted": 35,
        "extra_points_made": 35,
        "extra_point_percentage": 100.0,
    },
    "Mississippi": {
        "field_goals_attempted": 35,
        "field_goals_made": 31,
        "field_goal_percentage": 88.6,
        "extra_points_attempted": 59,
        "extra_points_made": 59,
        "extra_point_percentage": 100.0,
    },
    "UCF": {
        "field_goals_attempted": 17,
        "field_goals_made": 15,
        "field_goal_percentage": 88.2,
        "extra_points_attempted": 34,
        "extra_points_made": 33,
        "extra_point_percentage": 97.1,
    },
    "Purdue": {
        "field_goals_attempted": 17,
        "field_goals_made": 15,
        "field_goal_percentage": 88.2,
        "extra_points_attempted": 24,
        "extra_points_made": 24,
        "extra_point_percentage": 100.0,
    },
    "Maryland": {
        "field_goals_attempted": 24,
        "field_goals_made": 21,
        "field_goal_percentage": 87.5,
        "extra_points_attempted": 31,
        "extra_points_made": 31,
        "extra_point_percentage": 100.0,
    },
    "Auburn": {
        "field_goals_attempted": 25,
        "field_goals_made": 20,
        "field_goal_percentage": 80.0,
        "extra_points_attempted": 35,
        "extra_points_made": 35,
        "extra_point_percentage": 100.0,
    },
    "Illinois": {
        "field_goals_attempted": 23,
        "field_goals_made": 20,
        "field_goal_percentage": 87.0,
        "extra_points_attempted": 44,
        "extra_points_made": 44,
        "extra_point_percentage": 100.0,
    },
    "Pittsburgh": {
        "field_goals_attempted": 26,
        "field_goals_made": 21,
        "field_goal_percentage": 80.7,
        "extra_points_attempted": 50,
        "extra_points_made": 49,
        "extra_point_percentage": 98.0,
    },
    "Kansas State": {
        "field_goals_attempted": 15,
        "field_goals_made": 13,
        "field_goal_percentage": 86.7,
        "extra_points_attempted": 42,
        "extra_points_made": 42,
        "extra_point_percentage": 100.0,
    },
     "Georgia Tech": {
        "field_goals_attempted": 29,
        "field_goals_made": 25,
        "field_goal_percentage": 86.2,
        "extra_points_attempted": 45,
        "extra_points_made": 45,
        "extra_point_percentage": 100.0,
    },
    "Syracuse": {
        "field_goals_attempted": 14,
        "field_goals_made": 12,
        "field_goal_percentage": 85.7,
        "extra_points_attempted": 22,
        "extra_points_made": 22,
        "extra_point_percentage": 100.0,
    },
    "Mississippi State": {
        "field_goals_attempted": 20,
        "field_goals_made": 17,
        "field_goal_percentage": 85.0,
        "extra_points_attempted": 46,
        "extra_points_made": 46,
        "extra_point_percentage": 100.0,
    },
    "Nebraska": {
        "field_goals_attempted": 19,
        "field_goals_made": 16,
        "field_goal_percentage": 84.2,
        "extra_points_attempted": 45,
        "extra_points_made": 45,
        "extra_point_percentage": 100.0,
    },
    "Louisville": {
        "field_goals_attempted": 29,
        "field_goals_made": 23,
        "field_goal_percentage": 79.3,
        "extra_points_attempted": 43,
        "extra_points_made": 40,
        "extra_point_percentage": 93.0,
    },
    "USC": {
        "field_goals_attempted": 25,
        "field_goals_made": 21,
        "field_goal_percentage": 84.0,
        "extra_points_attempted": 50,
        "extra_points_made": 50,
        "extra_point_percentage": 100.0,
    },
    "West Virginia": {
        "field_goals_attempted": 12,
        "field_goals_made": 10,
        "field_goal_percentage": 83.3,
        "extra_points_attempted": 32,
        "extra_points_made": 31,
        "extra_point_percentage": 96.9,
    },
    "NC State": {
        "field_goals_attempted": 9,
        "field_goals_made": 6,
        "field_goal_percentage": 66.7,
        "extra_points_attempted": 52,
        "extra_points_made": 51,
        "extra_point_percentage": 98.1,
    },
    "Texas": {
        "field_goals_attempted": 24,
        "field_goals_made": 20,
        "field_goal_percentage": 83.3,
        "extra_points_attempted": 48,
        "extra_points_made": 48,
        "extra_point_percentage": 100.0,
    },
    "Notre Dame": {
        "field_goals_attempted": 9,
        "field_goals_made": 5,
        "field_goal_percentage": 55.6,
        "extra_points_attempted": 67,
        "extra_points_made": 63,
        "extra_point_percentage": 94.0,
    },
    "LSU": {
        "field_goals_attempted": 29,
        "field_goals_made": 24,
        "field_goal_percentage": 82.8,
        "extra_points_attempted": 30,
        "extra_points_made": 29,
        "extra_point_percentage": 96.7,
    },
    "North Carolina": {
        "field_goals_attempted": 23,
        "field_goals_made": 19,
        "field_goal_percentage": 82.6,
        "extra_points_attempted": 20,
        "extra_points_made": 20,
        "extra_point_percentage": 100.0,
    },
    "Kansas": {
        "field_goals_attempted": 17,
        "field_goals_made": 14,
        "field_goal_percentage": 82.4,
        "extra_points_attempted": 41,
        "extra_points_made": 41,
        "extra_point_percentage": 100.0,
    },
    "Colorado": {
        "field_goals_attempted": 12,
        "field_goals_made": 9,
        "field_goal_percentage": 75.0,
        "extra_points_attempted": 31,
        "extra_points_made": 30,
        "extra_point_percentage": 96.8,
    },
    "Wake Forest": {
        "field_goals_attempted": 22,
        "field_goals_made": 18,
        "field_goal_percentage": 81.8,
        "extra_points_attempted": 36,
        "extra_points_made": 35,
        "extra_point_percentage": 97.2,
    },
    "Baylor": {
        "field_goals_attempted": 22,
        "field_goals_made": 18,
        "field_goal_percentage": 81.8,
        "extra_points_attempted": 37,
        "extra_points_made": 37,
        "extra_point_percentage": 100.0,
    },
    "Florida": {
        "field_goals_attempted": 22,
        "field_goals_made": 18,
        "field_goal_percentage": 81.8,
        "extra_points_attempted": 28,
        "extra_points_made": 27,
        "extra_point_percentage": 96.4,
    },
    "Clemson": {
        "field_goals_attempted": 21,
        "field_goals_made": 17,
        "field_goal_percentage": 81.0,
        "extra_points_attempted": 41,
        "extra_points_made": 41,
        "extra_point_percentage": 100.0,
    },
    "Houston": {
        "field_goals_attempted": 26,
        "field_goals_made": 21,
        "field_goal_percentage": 80.8,
        "extra_points_attempted": 43,
        "extra_points_made": 43,
        "extra_point_percentage": 100.0,
    },
    "Ohio State": {
        "field_goals_attempted": 20,
        "field_goals_made": 16,
        "field_goal_percentage": 80.0,
        "extra_points_attempted": 60,
        "extra_points_made": 60,
        "extra_point_percentage": 100.0,
    },
    "UCLA": {
        "field_goals_attempted": 20,
        "field_goals_made": 16,
        "field_goal_percentage": 80.0,
        "extra_points_attempted": 22,
        "extra_points_made": 22,
        "extra_point_percentage": 100.0,
    },
    "Virginia": {
        "field_goals_attempted": 30,
        "field_goals_made": 24,
        "field_goal_percentage": 80.0,
        "extra_points_attempted": 49,
        "extra_points_made": 49,
        "extra_point_percentage": 100.0,
    },
    "South Carolina": {
        "field_goals_attempted": 16,
        "field_goals_made": 12,
        "field_goal_percentage": 75.0,
        "extra_points_attempted": 32,
        "extra_points_made": 32,
        "extra_point_percentage": 100.0,
    },
    "Oregon": {
        "field_goals_attempted": 25,
        "field_goals_made": 19,
        "field_goal_percentage": 76.0,
        "extra_points_attempted": 67,
        "extra_points_made": 67,
        "extra_point_percentage": 100.0,
    },

    "Iowa": {
        "field_goals_attempted": 28,
        "field_goals_made": 22,
        "field_goal_percentage": 78.6,
        "extra_points_attempted": 42,
        "extra_points_made": 41,
        "extra_point_percentage": 97.6,
    },
    "Iowa State": {
        "field_goals_attempted": 21,
        "field_goals_made": 16,
        "field_goal_percentage": 76.2,
        "extra_points_attempted": 33,
        "extra_points_made": 31,
        "extra_point_percentage": 94.0,
    },
    "Arkansas": {
        "field_goals_attempted": 18,
        "field_goals_made": 14,
        "field_goal_percentage": 77.8,
        "extra_points_attempted": 47,
        "extra_points_made": 47,
        "extra_point_percentage": 100.0,
    },
    "California": {
        "field_goals_attempted": 19,
        "field_goals_made": 14,
        "field_goal_percentage": 73.7,
        "extra_points_attempted": 39,
        "extra_points_made": 39,
        "extra_point_percentage": 100.0,
    },
    "Washington": {
        "field_goals_attempted": 13,
        "field_goals_made": 10,
        "field_goal_percentage": 76.9,
        "extra_points_attempted": 59,
        "extra_points_made": 59,
        "extra_point_percentage": 100.0,
    },
    "BYU": {
        "field_goals_attempted": 30,
        "field_goals_made": 23,
        "field_goal_percentage": 76.7,
        "extra_points_attempted": 49,
        "extra_points_made": 49,
        "extra_point_percentage": 100.0,
    },
    "Kentucky": {
        "field_goals_attempted": 17,
        "field_goals_made": 13,
        "field_goal_percentage": 76.5,
        "extra_points_attempted": 33,
        "extra_points_made": 33,
        "extra_point_percentage": 100.0,
    },
    "Cincinnati": {
        "field_goals_attempted": 17,
        "field_goals_made": 13,
        "field_goal_percentage": 76.5,
        "extra_points_attempted": 49,
        "extra_points_made": 49,
        "extra_point_percentage": 100.0,
    },
    "Stanford": {
        "field_goals_attempted": 21,
        "field_goals_made": 16,
        "field_goal_percentage": 76.2,
        "extra_points_attempted": 22,
        "extra_points_made": 22,
        "extra_point_percentage": 100.0,
    },
    "Virginia Tech": {
        "field_goals_attempted": 20,
        "field_goals_made": 15,
        "field_goal_percentage": 75.0,
        "extra_points_attempted": 26,
        "extra_points_made": 26,
        "extra_point_percentage": 100.0,
    },
    "Oklahoma State": {
        "field_goals_attempted": 20,
        "field_goals_made": 15,
        "field_goal_percentage": 75.0,
        "extra_points_attempted": 17,
        "extra_points_made": 17,
        "extra_point_percentage": 100.0,
    },
    "Michigan State": {
        "field_goals_attempted": 17,
        "field_goals_made": 12,
        "field_goal_percentage": 70.6,
        "extra_points_attempted": 34,
        "extra_points_made": 33,
        "extra_point_percentage": 97.1,
    },
    "Tennessee": {
        "field_goals_attempted": 19,
        "field_goals_made": 14,
        "field_goal_percentage": 73.7,
        "extra_points_attempted": 67,
        "extra_points_made": 67,
        "extra_point_percentage": 100.0,
    },
    "Duke": {
        "field_goals_attempted": 19,
        "field_goals_made": 14,
        "field_goal_percentage": 73.7,
        "extra_points_attempted": 56,
        "extra_points_made": 56,
        "extra_point_percentage": 100.0,
    },
    "Utah": {
        "field_goals_attempted": 15,
        "field_goals_made": 11,
        "field_goal_percentage": 73.3,
        "extra_points_attempted": 71,
        "extra_points_made": 68,
        "extra_point_percentage": 95.8,
    },
    "Arizona State": {
        "field_goals_attempted": 30,
        "field_goals_made": 22,
        "field_goal_percentage": 73.3,
        "extra_points_attempted": 33,
        "extra_points_made": 33,
        "extra_point_percentage": 100.0,
    },
    "Rutgers": {
        "field_goals_attempted": 19,
        "field_goals_made": 13,
        "field_goal_percentage": 68.4,
        "extra_points_attempted": 41,
        "extra_points_made": 39,
        "extra_point_percentage": 95.1,
    },
    "SMU": {
        "field_goals_attempted": 22,
        "field_goals_made": 15,
        "field_goal_percentage": 68.2,
        "extra_points_attempted": 52,
        "extra_points_made": 50,
        "extra_point_percentage": 96.2,
    },
    "Alabama": {
        "field_goals_attempted": 23,
        "field_goals_made": 16,
        "field_goal_percentage": 69.6,
        "extra_points_attempted": 55,
        "extra_points_made": 55,
        "extra_point_percentage": 100.0,
    },
    "Michigan": {
        "field_goals_attempted": 25,
        "field_goals_made": 17,
        "field_goal_percentage": 68.0,
        "extra_points_attempted": 43,
        "extra_points_made": 43,
        "extra_point_percentage": 100.0,
    },
    "Minnesota": {
        "field_goals_attempted": 21,
        "field_goals_made": 14,
        "field_goal_percentage": 66.7,
        "extra_points_attempted": 35,
        "extra_points_made": 35,
        "extra_point_percentage": 100.0,
    },
    "Wisconsin": {
        "field_goals_attempted": 11,
        "field_goals_made": 7,
        "field_goal_percentage": 63.6,
        "extra_points_attempted": 19,
        "extra_points_made": 19,
        "extra_point_percentage": 100.0,
    },
    "Florida State": {
        "field_goals_attempted": 19,
        "field_goals_made": 12,
        "field_goal_percentage": 63.2,
        "extra_points_attempted": 48,
        "extra_points_made": 48,
        "extra_point_percentage": 100.0,
    },
    "Texas A&M": {
        "field_goals_attempted": 23,
        "field_goals_made": 16,
        "field_goal_percentage": 69.5,
        "extra_points_attempted": 56,
        "extra_points_made": 55,
        "extra_point_percentage": 98.2,
    },
    "Arizona": {
        "field_goals_attempted": 32,
        "field_goals_made": 19,
        "field_goal_percentage": 59.3,
        "extra_points_attempted": 48,
        "extra_points_made": 47,
        "extra_point_percentage": 97.9,
    },
}