from models import Team, TeamStats

teams: dict[int, Team] = {
    1: Team(
        id=1,
        name="USC",
        conference="Big Ten",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    2: Team(
        id=2,
        name="Oregon",
        conference="Big Ten",
        wins=13,
        losses=2,
        stats=TeamStats(),
    ),
    3: Team(
        id=3,
        name="Indiana",
        conference="Big Ten",
        wins=16,
        losses=0,
        stats=TeamStats(),
    ),
    4: Team(
        id=4,
        name="Ohio State",
        wins=12,
        losses=2,
        conference="Big Ten",
        stats=TeamStats(),
    ),
    5: Team(
        id=5,
        name="Washington",
        conference="Big Ten",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    6: Team(
        id=6,
        name="Rutgers",
        conference="Big Ten",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    7: Team(
        id=7,
        name="Michigan",
        conference="Big Ten",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    8: Team(
        id=8,
        name="Maryland",
        conference="Big Ten",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    9: Team(
        id=9,
        name="Northwestern",
        conference="Big Ten",
        wins=7,
        losses=6,
        stats=TeamStats(),
    ),
    10: Team(
        id=10,
        name="Illinois",
        conference="Big Ten",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    11: Team(
        id=11,
        name="Nebraska",
        conference="Big Ten",
        wins=7,
        losses=6,
        stats=TeamStats(),
    ),
    12: Team(
        id=12,
        name="Penn State",
        conference="Big Ten",
        wins=7,
        losses=6,
        stats=TeamStats(),
    ),
    13: Team(
        id=13,
        name="Purdue",
        conference="Big Ten",
        wins=2,
        losses=10,
        stats=TeamStats(),
    ),
    14: Team(
        id=14,
        name="Michigan State",
        conference="Big Ten",
        wins=4,
        losses=8,
        stats=TeamStats(),
    ),
    15: Team(
        id=15,
        name="Iowa",
        conference="Big Ten",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    16: Team(
        id=16,
        name="UCLA",
        conference="Big Ten",
        wins=3,
        losses=9,
        stats=TeamStats(),
    ),
    17: Team(
        id=17,
        name="Minnesota",
        conference="Big Ten",
        wins=8,
        losses=5,
        stats=TeamStats(),
    ),
    18: Team(
        id=18,
        name="Wisconsin",
        conference="Big Ten",
        wins=4,
        losses=8,
        stats=TeamStats(),
    ),
    19: Team(
        id=19,
        name="Florida State",
        conference="ACC",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    20: Team(
        id=20,
        name="Georgia Tech",
        conference="ACC",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    21: Team(
        id=21,
        name="Duke",
        conference="ACC",
        wins=9,
        losses=5,
        stats=TeamStats(),
    ),
    22: Team(
        id=22,
        name="Virginia",
        conference="ACC",
        wins=11,
        losses=3,
        stats=TeamStats(),
    ),
    23: Team(
        id=23,
        name="SMU",
        conference="ACC",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    24: Team(
        id=24,
        name="Miami",
        conference="ACC",
        wins=13,
        losses=3,
        stats=TeamStats(),
    ),
    25: Team(
        id=25,
        name="Wake Forest",
        conference="ACC",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    26: Team(
        id=26,
        name="Clemson",
        conference="ACC",
        wins=7,
        losses=6,
        stats=TeamStats(),
    ),
    27: Team(
        id=27,
        name="NC State",
        conference="ACC",
        wins=8,
        losses=5,
        stats=TeamStats(),
    ),
    28: Team(
        id=28,
        name="Louisville",
        conference="ACC",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    29: Team(
        id=29,
        name="Pittsburgh",
        conference="ACC",
        wins=8,
        losses=5,
        stats=TeamStats(),
    ),
    30: Team(
        id=30,
        name="Boston College",
        conference="ACC",
        wins=2,
        losses=10,
        stats=TeamStats(),
    ),
    31: Team(
        id=31,
        name="California",
        conference="ACC",
        wins=7,
        losses=6,
        stats=TeamStats(),
    ),
    32: Team(
        id=32,
        name="Virginia Tech",
        conference="ACC",
        wins=3,
        losses=9,
        stats=TeamStats(),
    ),
    33: Team(
        id=33,
        name="Syracuse",
        conference="ACC",
        wins=3,
        losses=9,
        stats=TeamStats(),
    ),
    34: Team(
        id=34,
        name="Stanford",
        conference="ACC",
        wins=4,
        losses=8,
        stats=TeamStats(),
    ),
    35: Team(
        id=35,
        name="North Carolina",
        conference="ACC",
        wins=4,
        losses=8,
        stats=TeamStats(),
    ),
    36: Team(
        id=36,
        name="Utah",
        conference="Big 12",
        wins=11,
        losses=2,
        stats=TeamStats(),
    ),
    37: Team(
        id=37,
        name="Texas Tech",
        conference="Big 12",
        wins=12,
        losses=2,
        stats=TeamStats(),
    ),
    38: Team(
        id=38,
        name="Baylor",
        conference="Big 12",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    39: Team(
        id=39,
        name="TCU",
        conference="Big 12",
        wins=9,
        losses=4,
        stats=TeamStats(),
    ),
    40: Team(
        id=40,
        name="Cincinnati",
        conference="Big 12",
        wins=7,
        losses=6,
        stats=TeamStats(),
    ),
    41: Team(
        id=41,
        name="Arizona State",
        conference="Big 12",
        wins=8,
        losses=5,
        stats=TeamStats(),
    ),
    42: Team(
        id=42,
        name="BYU",
        conference="Big 12",
        wins=12,
        losses=2,
        stats=TeamStats(),
    ),
    43: Team(
        id=43,
        name="Arizona",
        conference="Big 12",
        wins=6,
        losses=4,
        stats=TeamStats(),
    ),
    44: Team(
        id=44,
        name="Houston",
        conference="Big 12",
        wins=10,
        losses=3,
        stats=TeamStats(),
    ),
    45: Team(
        id=45,
        name="Iowa State",
        conference="Big 12",
        wins=8,
        losses=4,
        stats=TeamStats(),
    ),
    46: Team(
        id=46,
        name="Kansas",
        conference="Big 12",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    47: Team(
        id=47,
        name="UCF",
        conference="Big 12",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    48: Team(
        id=48,
        name="Kansas State",
        conference="Big 12",
        wins=6,
        losses=6,
        stats=TeamStats(),
    ),
    49: Team(
        id=49,
        name="West Virginia",
        conference="Big 12",
        wins=4,
        losses=8,
        stats=TeamStats(),
    ),
    50: Team(
        id=50,
        name="Colorado",
        conference="Big 12",
        wins=3,
        losses=9,
        stats=TeamStats(),
    ),
    51: Team(
        id=51,
        name="Oklahoma State",
        conference="Big 12",
        wins=1,
        losses=11,
        stats=TeamStats(),
    ),
    52: Team(
        id=52,
        name="Mississippi",
        conference="SEC",
        wins=13,
        losses=2,
        stats=TeamStats(),
    ),
    53: Team(
        id=53,
        name="Tennessee",
        conference="SEC",
        wins=8,
        losses=5,
        stats=TeamStats(),
    ),
    54: Team(
        id=54,
        name="Vanderbilt",
        conference="SEC",
        wins=10,
        losses=3,
        stats=TeamStats(),
    ),
    55: Team(
        id=55,
        name="Texas A&M",
        conference="SEC",
        wins=11,
        losses=2,
        stats=TeamStats(),
    ),
    56: Team(
        id=56,
        name="Arkansas",
        conference="SEC",
        wins=2,
        losses=10,

        stats=TeamStats(),
    ),
    57: Team(
        id=57,
        name="Missouri",
        conference="SEC",
        wins=8,
        losses=5,
        stats=TeamStats(),
    ),
    58: Team(
        id=58,
        name="Georgia",
        conference="SEC",
        wins=12,
        losses=2,
        stats=TeamStats(),
    ),
    59: Team(
        id=59,
        name="Texas",
        conference="SEC",
        wins=10,
        losses=3,
        stats=TeamStats(),
    ),
    60: Team(
        id=60,
        name="Mississippi State",
        conference="SEC",
        wins=5,
        losses=8,
        stats=TeamStats(),
    ),
    61: Team(
        id=61,
        name="Auburn",
        conference="SEC",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    62: Team(
        id=62,
        name="Alabama",
        conference="SEC",
        wins=11,
        losses=4,
        stats=TeamStats(),
    ),
    63: Team(
        id=63,
        name="Oklahoma",
        conference="SEC",
        wins=10,
        losses=3,
        stats=TeamStats(),
    ),
    64: Team(
        id=64,
        name="Florida",
        conference="SEC",
        wins=4,
        losses=8,
        stats=TeamStats(),
    ),
    65: Team(
        id=65,
        name="Kentucky",
        conference="SEC",
        wins=5,
        losses=7,
        stats=TeamStats(),
    ),
    66: Team(
        id=66,
        name="LSU",
        conference="SEC",
        wins=7,
        losses=6,
        stats=TeamStats(),
    ),
    67: Team(
        id=67,
        name="South Carolina",
        conference="SEC",
        wins=4,
        losses=8,
        stats=TeamStats(),
    ),
    68: Team(
        id=68,
        name="Notre Dame",
        conference="Independent",
        wins=10,
        losses=2,
        stats=TeamStats(),
    ),
}